backend:
  name: github
  repo: rapsamaniego27/portfolio-2020
  branch: master

media_folder: "images"

# Allows which files or folders Netlify can edit

collections:
  - name: "home"
    label: "Home Page"
    files:
    - label: "Home Content"
      name: "site"
      file: "_data/main.yml"
      fields:
       - label: "Tagline"
         name: "tagline"
         width: "string"
       - label: "Occupation"
         name: "occupation"
         width: "string"
       - label: "Summary"
         name: "summary"
         width: "text"

  - label: "Sample Projects"
    name: "sample-projects"
    create: true
    folder: "_samples"
    fields:
      - label: "Title"
        name: "title"
        width: "string"
      - label: "Link"
        name: "link"
        width: "string"
      - label: "Thumbnail"
        name: "thumbnail"
        width: "image"

  - label: "Core Technologies"
    name: "core-technologies"
    create: true
    folder: "_cores"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Stars"
        name: "link"
        widget: "number"
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["Design", "Code"]    

  - label: "Chapters"
    name: "chapters"
    create: true
    folder: "_posts"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "chapter"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        default: "Rap Esteva"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Thumbnail(570 x 440)"
        name: "image"
        widget: "image"
      - label: "Banner(1130 x 250)"
        name: "banner"
        widget: "image"
      - label: "Categories"
        name: "category"
        widget: "list"
      - label: "Meta(Body)"
        name: "body"
        widget: "text"
        pattern: ['^.{20,170}$', "Must be in between 20 - 170 characters"]
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        required: false
        fields:
          - label: "alignment"
            name: "alignment"
            widget: "select"
            options: ["one column", "two columns", "two columns reverse"]
            default: ["one column"]
          - label: "Content"
            name: "content"
            widget: "object"
            required: false
            fields: 
              - label: Text (300 - 420 for 2 columns)
                name: text
                widget: markdown
              - label: Image(280 x 194)
                name: image
                widget: image
                required: false
              

