backend:
  name: github
  repo: rapsamaniego27/portfolio-2020
  branch: master

media_folder: "images"

# Allows which files or folders Netlify can edit

collections:
  - name: "home"
    label: "Defaults"
    files:
    - label: "Default Content"
      name: "site"
      file: "_data/main.yml"
      fields:
       - label: "Tagline"
         name: "tagline"
         widget: "string"
       - label: "Occupation"
         name: "occupation"
         widget: "string"
       - label: "Summary"
         name: "summary"
         widget: "markdown"
       - label: "Note (to be added in Contact Form)"
         name: "note"
         widget: "text"
         required: false
       - label: "Resume"
         name: "resume"
         widget: "file"
         required: false
       - label: "CV"
         name: "cv"
         widget: "file"
         required: false 
       - label: "Technologies Used"
         name: "technologies"
         widget: "list"
       - label: "Collaborators"
         name: "collaborators"
         widget: "list"
         required: false
         fields:
          - label: "Content"
            name: "content"
            widget: "object"
            required: false
            fields: 
              - label: "Name"
                name: "name"
                widget: "string"
                required: false
              - label: "Website"
                name: "website"
                widget: "string"
                required: false
       
      
  - label: "Pages"
    name: "pages"
    create: true
    folder: "_pages"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Meta Description"
        name: "meta_description"
        widget: "text"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "string"
      - label: "Meta Image"
        name: "meta_image"
        widget: "image"
        required: false

  - label: "Sample Projects"
    name: "sample-projects"
    create: true
    folder: "_samples"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Link"
        name: "link"
        widget: "string"
      - label: "Thumbnail"
        name: "thumbnail"
        widget: "image"

  - label: "Core Technologies"
    name: "core-technologies"
    create: true
    folder: "_cores"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Stars"
        name: "stars"
        widget: "number"
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["Design", "Code"]    

  - label: "Work Experience"
    name: "jobs"
    create: true
    folder: "_jobs"
    fields:
      - label: "Company"
        name: "company"
        widget: "string"
      - label: "Position"
        name: "position"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Start date"
        name: "start_date"
        widget: 'date'
        default: ''
        format: 'MMM YYYY'
        time_format: false
      - label: "End date"
        name: "end_date"
        widget: 'date'
        default: ''
        format: 'MMM YYYY'
        time_format: false
        required: false
      - label: Logo (Not more than 300px wide)
        name: logo
        widget: image
        required: false

  - label: "Chapters"
    name: "chapters"
    create: true
    folder: "_posts"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "chapter"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        default: "Rap Esteva"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Thumbnail(570 x 440)"
        name: "image"
        widget: "image"
      - label: "Banner(1130 x 250)"
        name: "banner"
        widget: "image"
      - label: "Categories"
        name: "category"
        widget: "list"
      - label: "Meta(Body)"
        name: "description"
        widget: "text"
        pattern: ['^.{20,170}$', "Must be in between 20 - 170 characters"]
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        required: false
        fields:
          - label: "alignment"
            name: "alignment"
            widget: "select"
            options: ["one column", "two columns", "two columns reverse"]
            default: ["one column"]
          - label: "Content"
            name: "content"
            widget: "object"
            required: false
            fields: 
              - label: Text (300 - 420 for 2 columns)
                name: text
                widget: markdown
              - label: Image(280 x 194)
                name: image
                widget: image
                required: false
              

