backend:
  name: github
  repo: rapsamaniego27/portfolio-2020
  branch: master

media_folder: "images"

# Allows which files or folders Netlify can edit

collections:
  - name: "home"
    label: "Home Page"
    files:
    - label: "Home Content"
      name: "site"
      file: "_data/main.yml"
      fields:
       - label: "Tagline"
         name: "tagline"
         width: "string"
       - label: "Occupation"
         name: "occupation"
         width: "string"
       - label: "Summary"
         name: "summary"
         width: "text"

  - label: "Sample Projects"
    name: "sample-projects"
    create: true
    folder: "_samples"
    fields:
      - label: "Title"
        name: "title"
        width: "string"
      - label: "Link"
        name: "link"
        width: "string"
      - label: "Thumbnail"
        name: "thumbnail"
        width: "image"
       

  - label: "Chapters"
    name: "chapters"
    create: true
    folder: "_posts"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "chapter"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Author"
        name: "author"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Banner"
        name: "banner"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Categories"
        name: "category"
        widget: "list"
      - label: "Meta"
        name: "meta"
        widget: "markdown"
        default: '{{body.excerpt}}'
      - label: "Profile"
        name: "profile"
        widget: "object"
        summary: '{{fields.name}}: {{fields.birthdate}}'
        fields:
          - {label: "Public", name: "public", widget: "boolean", default: true}
          - {label: "Name", name: "name", widget: "string"}
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Street Address", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Postal Code", name: "post-code", widget: "string"}
      

