backend:
  name: github
  repo: rapsamaniego27/portfolio-2020
  branch: master

media_folder: "images"

# Allows which files or folders Netlify can edit

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
    - label: "Website settings"
      name: "site"
      file: "_data/main.yml"
      fields:
       - label: "Tagline"
         name: "tagline"
         width: "string"