backend:
  name: github
  repo: rapsamaniego27/portfolio-2020
  branch: master

media_folder: "images"

# Allows which files or folders Netlify can edit

collections:
  - name: "home"
    label: "Home Page"
    files:
    - label: "Home Content"
      name: "site"
      file: "_data/main.yml"
      fields:
       - label: "Tagline"
         name: "tagline"
         width: "string"
       - label: "Occupation"
         name: "occupation"
         width: "string"
       - label: "Summary"
         name: "summary"
         width: "text"

    - label: "Sample Projects"
      name: "sample-projects"
      create: true
      folder: "_samples"
      fields:
       - label: "Layout"
         name: "layout"
         width: "hidden"
         default: "sample"
       - label: "Name"
         name: "name"
         width: "string"
       - label: "Link"
         name: "link"
         width: "string"
       - label: "Thumbnail"
         name: "thumbnail"
         width: "image"
       